### ISSUE TITLE
calculate-go-stats.py: format for GO file

### ISSUE THREAD

**Issue by sformel** [GGFHF/NGShelper#1]
I'm working with TOA and finding it very easy and useful, thank you!  

Following the TOA paper, I've looked to this package for doing a GO enrichment analysis.  This is the first time I've ever tried to do such an analysis, so I'm still wrapping my head around GO terms.  What is the file format that is necessary for the GO file input?  Or even more explicitly, could you share a link to download the file that would make sense to use with TOA annotation file?  Thank you in advance!

**Comment by GGFHF** [comment]
Dear Stephen,

 thanks for using TOA and NGShelper. If you want to perform singular enrichment analyisis (SEA) using AGRIGO (http://systemsbiology.cau.edu.cn/agriGOv2/), you don't need to use calculate-go-stats.py. You can open the go-stats.csv  file from the stats directory output by TOA and copy the first column in the second column of a new spreadsheet. Use an arbitrary ID for each GO term in the first column so as to get a file like this:

Your_ID1	GO:0008150
Your_ID2	GO:0006468
Your_ID3	GO:0016301
Your_ID4	GO:0006499
Your_ID5	GO:0006499
Your_ID6	GO:0005499
Your_ID7	GO:0004569
Your_ID7	GO:0004565
Your_ID7	GO:0004568 

This is the input you should copy into the Agrigo v2 SEA box using "customized annotation". The output of AgriGO will show the enriched terms according the most suitable reference you define, and you can use that output with enriched GO terms and a p-value to further run REVIGO and reduce enriched GO term redundancy using semantic similarity.

Alternatively, you can run calculate-go-stats.py using as input the plant-annotation.csv file produced by TOA and the go.obo file downloaded from Gene Ontology page (http://geneontology.org/docs/download-ontology/). You can modify the bash script in NGShelper accordingly.

If you run this script successfully you will find three output files: toa-go-frequency.csv, toa-go-per-seq.csv and toa-seq-per-go.csv. In toa-go-frequency.csv, you can select the first and fourth column to have the count number of each GO term in your transcriptome, that can also be used to feed REVIGO.

Hope this helps. Please, let us know if you need further assistance.

All the best,

Unai and Fernando

**Comment by sformel** [comment]
Unai and Fernando,

Thank you for the quick and thoughtful answer!  I've been trying out AgriGO and REVIGO and continuing to read up on SEA.  In the literature, there is a lot of emphasis on choosing the correct background reference.  My organism is  _Spartina alterniflora_, so I prioritized the Monocot database and it makes sense to focus on homologies to rice in particular.  

It's not clear to me what I should use as my background reference in AgriGO.  When I enter a custom reference set, the result always says the background is "Arabidopsis genemodel (TAIR9)".  So perhaps I'm formatting the reference set incorrectly? 

* If I use your example above for the query list in step 2 of AgriGO SEA, what should the list look like in the box for step 3?  

I realize these questions might be more appropriate for the developers of AgriGO, but I thought I would ask here first since you understand what my output from annotation looks like.

It has also occurred to me that the problem might be my approach.  My annotation in TOA was only run on differentially expressed transcripts, so my GO stats reflect the GO terms from a specific set of genes.  Should I run another annotation of the entire transcriptome to create a baseline set of GO terms?  Or, is it possible to get the full set of GO terms from the monocot database and apply dummy gene IDs to them?

Again, I thank you in advance for your help!

Steve

**Comment by GGFHF** [comment]
Hi Steve,

Regarding your first issue, if you use AgriGO v2 (http://systemsbiology.cau.edu.cn/agriGOv2/):
Analysis-->Plant-->Poaceae, in step 2 select Oryza sativa (or the closest model species to your species) first, and then, press Customized annotation. The backgrounds in the 3rd step should change to fit your needs. You have many backgrounds for Oryza, but also for other Poaceae.
Regarding your last question. As far as I know, you can run any set of GO terms (the whole transcriptome, only differentially expressed, only up-regulated, only down-regulated...). It will depend on the aims of your study, number of samples,  number of biological replicates, etc....
Hope this helps and you can get sound results in your work.
All the best!
Unai and Fernando

**Comment by sformel** [comment]
That cleared it up, thank you!
